### ISSUE TITLE
Could not find a declaration file for module '@editorjs/quote'

### ISSUE THREAD

**Issue by Ashish-3000** [editor-js/quote#44]
Try `npm i --save-dev @types/editorjs__quote if it exists or add a new declaration (.d.ts) file containing `declare module '@editorjs/quote';` 
This error is showing for all editorjs files except header and editorjs.

Can you publish other npm packages for typescript

**Comment by rodriguezz4060** [comment]
Create a listing file:
In the root of your project, create the editorjs.d.ts file and add the following content to it:

`declare module '@editorjs/quote'`

tsconfig.json

`{
  "include": [
    "./editorjs.d.ts",
    // other files and folders to be included
  ],
//other settings
}`

**Comment by neSpecc** [comment]
Resolved by #67
