### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by max-frai** [editor-js/quote#68]
Hi, 
```
Couldn't find any versions for "@editorjs/helpers" that matches "workspace:*"
? Please choose a version of "@editorjs/helpers" from this list: (Use arrow keys)
❯ 0.0.1 
```

quote refers to editorjs/dom and it refers to editorjs/helpers which can't be resolved.

---

Looks like this "workspace:*" is valid for pnpm/yarn2, but nextjs doesn't support yarn2 and also yarn is more popular than pnpm.

**Comment by reoharada** [comment]
Hello. I'm encountering the same issue. 
```
$ npm install --save @editorjs/dom
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:*
npm error A complete log of this run can be found in: /Users/**********/.npm/_logs/2024-08-17T07_30_42_775Z-debug-0.log
```

I suspect there might be a problem with the `package.json` of `@editorjs/dom`.

In the package.json, under dependencies, I noticed this:
```
"dependencies": {
  "@editorjs/helpers": "workspace:*"
}
```
https://www.npmjs.com/package/@editorjs/dom?activeTab=code

The version of `@editorjs/helpers` is set to `workspace:*`. How should I address this?

**Comment by Sozialarchiv** [comment]
Same here

**Comment by Sozialarchiv** [comment]
@aavishkarmishra 
@neSpecc

**Comment by VityaSchel** [comment]
Workaround: `bun add @editorjs/quote@2.6.0`

**Comment by HemmingAskodan** [comment]
I'm having same issue.

**Comment by axelys** [comment]
same problem too

**Comment by Sozialarchiv** [comment]
@e11sy Thank you very much.
